version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=n8n
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=mysecretpassword
      - N8N_CUSTOM_EXTENSIONS_DIR=/home/node/.n8n/custom
      - NODE_ENV=development
    ports:
      - "5678:5678"
    volumes:
      - ./nodes:/home/node/.n8n/custom
    depends_on:
      - postgres

volumes:
  postgres_data: